#!/bin/bash

# $1 == job_id

RM='unknown'
QDEL=''
SCANCEL=''
set -o pipefail

function usage {
	echo "Usage: $0 job_id"
}

function report_error {
	echo -e "$1"
}

function report_success {
	echo -e "{\n\t\"result\": \"OK\"\n}"
}

function detect_rm {
	SCANCEL=$(which scancel 2>/dev/null)
	if [ $? -eq 0 ]
	then
		RM="slurm"
		return
	fi
	
	QDEL=$(which qdel 2>/dev/null)
	if [ $? -eq 0 ]
	then
		RM="torque"
	fi
}

function stop_torque {
	output=$(${QDEL} $1 2>&1)

	if [ $? -ne 0 ]
	then
		report_error "qsub error! $output"
		exit 12
	fi

	report_success
}

function stop_slurm {
	job_id=`[[ $1 =~ (^[0-9]*) ]] && echo $BASH_REMATCH`
	output=$(${SCANCEL} $job_id 2>&1)

	if [ $? -ne 0 ]
	then
		report_error "scancel error! $output"
		exit 22
	fi

	report_success
}

if [ -z "$1" ]
then
	usage
	exit 1
fi

detect_rm

if [ "$RM" == "torque" ]
then
	stop_torque $1
elif [ "$RM" == "slurm" ]
then
	stop_slurm $1
else
	report_error "Unable to determine resource manager"
	exit 2
fi
